# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [4]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [35]:
A = [0] * 1000
sys.getsizeof(A)

8056

In [34]:
B = np.zeros(1000, dtype=np.int8)
sys.getsizeof(B)

1112

## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [47]:
import random

small_float_array = np.array([random.uniform(0, 10.0) for _ in range(10)], dtype=np.float16)

print(small_float_array)

first = small_float_array[0]
third = small_float_array[2]
last = small_float_array[-1]

print(first, third, last)


[9.086  9.52   6.53   8.95   4.215  2.852  7.67   0.1205 3.773  0.569 ]
9.086 6.53 0.569


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [80]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1], dtype=np.float16)
result = array[1] + array[5] + array[4] + array[2]
np.ceil(result)

np.float16(27.0)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [71]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [74]:
A.mean(axis=0)

[2.  8.4]


### Task 5.2 Get the standard deviation by `y` axis

In [76]:
A.std(axis=1)

[2.5 3.  4.  3.5 3. ]


### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [77]:
A.sum(axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [79]:
A[:2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [130]:
A[::2]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [151]:
# Python code
import time

start = time.time()
python_array = [i for i in range(1000000)]

p_time = time.time() - start

print("time spent for python array:", p_time)


time spent for python array: 0.047701358795166016


In [152]:
# write your numpy code here and estimate the time of execution

# Numpy array
start = time.time()
numpy_array = np.arange(1000000, dtype=np.int32)

np_time = time.time() - start
print("time spent for numpy array:", np_time)


print("numpy array faster than python:", p_time - np_time)

time spent for numpy array: 0.0
numpy array faster than python: 0.047701358795166016


### Task 6.2

In [163]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)
unknown_signature(vector1, vector2)

CPU times: total: 0 ns
Wall time: 0 ns


32

In [167]:
# write your numpy code here and estimate the time of execution
    
np_vector1 = np.array(vector1, dtype=np.int8)
np_vector2 = np.array(vector2, dtype=np.int8)

%time np.sum(np.multiply(np_vector1, np_vector2), dtype=np.int8)


CPU times: total: 0 ns
Wall time: 0 ns


np.int8(32)

### Task 6.3

In [168]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%time unknown_signature(matrix1, matrix2)

CPU times: total: 0 ns
Wall time: 0 ns


[[5, 12], [21, 32]]

In [174]:
# write your numpy code here and estimate the time of execution

np_matrix1 = np.array(matrix1, dtype=np.int8)
np_matrix2 = np.array(matrix2, dtype=np.int8)

%time np.multiply(np_matrix1, np_matrix2, dtype=np.int8)

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 5, 12],
       [21, 32]], dtype=int8)

### Task 6.4

In [175]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]
%time unknown_signature(lst)

CPU times: total: 0 ns
Wall time: 0 ns


3.0

In [181]:
# write your numpy code here and estimate the time of execution
np_lst = np.array(lst, dtype=np.int8)
%time np.average(np_lst)

CPU times: total: 0 ns
Wall time: 0 ns


np.float64(3.0)

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [81]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [82]:
# write your numpy code here
np_lst = np.array(lst, dtype=np.int8)
np_mask = np.array(mask, dtype=bool)
np.where(np_mask, 0, np_lst)


array([0, 2, 0, 4, 0], dtype=int8)

### Task 7.2

In [26]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [30]:
# write your numpy code here

np_list1 = np.array(list1, dtype=np.int8)
np_list2 = np.array(list2, dtype=np.int8)

%time np.bitwise_not(np_list1), np.bitwise_and(np_list1, np_list2), np.bitwise_or(np_list1, np_list2)

CPU times: total: 0 ns
Wall time: 0 ns


(array([ -6,  -3,  -8,  -5, -10], dtype=int8),
 array([1, 2, 1, 0, 8], dtype=int8),
 array([ 7,  6,  7, 12, 11], dtype=int8))

### Task 7.3 Optional

In [49]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [55]:
# write your numpy code here
np_my_list = np.array(my_list, dtype=np.int8)
%time np.where((np_my_list % 2 == 0) & ((np_my_list % 3 == 0) | (np_my_list > 10)), (np_my_list ^ 7) + 2, np.nan)

CPU times: total: 0 ns
Wall time: 0 ns


array([ 3., nan, 13., 11., nan, 21.])